#!/usr/bin/env python
# -*- coding: UTF8 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Mon Sep 15 19:30:20 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from gui_engine import *


class LearningEstimationPane(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LearningEstimationPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.learning_estimation_object_panel = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_1 = wx.TextCtrl(self.learning_estimation_object_panel, wx.ID_ANY, _(u"\u30d5\u30a1\u30a4\u30eb\u30d1\u30b9\u3092\u5165\u529b"))
        self.button_1 = wx.Button(self.learning_estimation_object_panel, wx.ID_ANY, _(u"\u53c2\u7167"))
        self.sizer_6_staticbox = wx.StaticBox(self.learning_estimation_object_panel, wx.ID_ANY, _(u"\u63a8\u5b9a\u5bfe\u8c61"))
        self.algorithm_panel = wx.Panel(self, wx.ID_ANY)
        self.algorithm_combo_box = wx.ComboBox(self.algorithm_panel, wx.ID_ANY, choices=[_("SVM"), _("Random Forest"), _("AdaBoost + Decision Tree"), _("AdaBoost + Naive Bayes")], style=wx.CB_DROPDOWN)
        self.sizer_8_staticbox = wx.StaticBox(self.algorithm_panel, wx.ID_ANY, _(u"\u5b66\u7fd2\u30a2\u30eb\u30b4\u30ea\u30ba\u30e0"))
        self.model_parameter_panel = wx.Panel(self, wx.ID_ANY)
        self.label_2 = wx.StaticText(self.model_parameter_panel, wx.ID_ANY, _(u"\u30ab\u30fc\u30cd\u30eb :"))
        self.combo_box_2 = wx.ComboBox(self.model_parameter_panel, wx.ID_ANY, choices=[_("Linear"), _("RBF")], style=wx.CB_DROPDOWN)
        self.label_3 = wx.StaticText(self.model_parameter_panel, wx.ID_ANY, _("C :"))
        self.text_ctrl_2 = wx.TextCtrl(self.model_parameter_panel, wx.ID_ANY, "")
        self.label_4 = wx.StaticText(self.model_parameter_panel, wx.ID_ANY, _("gamma :"))
        self.text_ctrl_3 = wx.TextCtrl(self.model_parameter_panel, wx.ID_ANY, "")
        self.sizer_9_staticbox = wx.StaticBox(self.model_parameter_panel, wx.ID_ANY, _(u"\u30e2\u30c7\u30eb\u30d1\u30e9\u30e1\u30fc\u30bf"))
        self.estimation_execution_panel = wx.Panel(self, wx.ID_ANY)
        self.estimation_execution_button = wx.Button(self.estimation_execution_panel, wx.ID_ANY, _(u"\u63a8\u5b9a"))
        self.panel_5 = wx.Panel(self, wx.ID_ANY)
        self.list_ctrl_1 = wx.ListCtrl(self.panel_5, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LearningEstimationPane.__set_properties
        self.learning_estimation_object_panel.SetMinSize((456, 60))
        self.learning_estimation_object_panel.SetBackgroundColour(wx.Colour(240, 240, 240))
        self.algorithm_combo_box.SetSelection(-1)
        self.algorithm_panel.SetMinSize((456, 60))
        self.algorithm_panel.SetBackgroundColour(wx.Colour(240, 240, 240))
        self.combo_box_2.SetSelection(-1)
        self.model_parameter_panel.SetBackgroundColour(wx.Colour(240, 240, 240))
        self.estimation_execution_panel.SetBackgroundColour(wx.Colour(240, 240, 240))
        self.panel_5.SetBackgroundColour(wx.Colour(240, 240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LearningEstimationPane.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_9_staticbox.Lower()
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 0, 0)
        self.sizer_8_staticbox.Lower()
        sizer_8 = wx.StaticBoxSizer(self.sizer_8_staticbox, wx.HORIZONTAL)
        self.sizer_6_staticbox.Lower()
        sizer_6 = wx.StaticBoxSizer(self.sizer_6_staticbox, wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add(self.text_ctrl_1, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        self.learning_estimation_object_panel.SetSizer(sizer_6)
        sizer_5.Add(self.learning_estimation_object_panel, 0, wx.TOP | wx.EXPAND, 10)
        sizer_8.Add(self.algorithm_combo_box, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.algorithm_panel.SetSizer(sizer_8)
        sizer_5.Add(self.algorithm_panel, 0, wx.TOP | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_2, 0, wx.RIGHT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.combo_box_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.RIGHT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.RIGHT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 10)
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_9.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.model_parameter_panel.SetSizer(sizer_9)
        sizer_5.Add(self.model_parameter_panel, 1, wx.TOP | wx.EXPAND, 10)
        sizer_10.Add(self.estimation_execution_button, 0, wx.BOTTOM | wx.ALIGN_RIGHT, 20)
        self.estimation_execution_panel.SetSizer(sizer_10)
        sizer_5.Add(self.estimation_execution_panel, 0, wx.EXPAND, 0)
        sizer_11.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        self.panel_5.SetSizer(sizer_11)
        sizer_5.Add(self.panel_5, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)
        # end wxGlade

# end of class LearningEstimationPane

class TuningPane(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TuningPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: TuningPane.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: TuningPane.__do_layout
        pass
        # end wxGlade

# end of class TuningPane

class DataModificationPane(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DataModificationPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.record_append_panel = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_4 = wx.TextCtrl(self.record_append_panel, wx.ID_ANY, _(u"\u30d5\u30a1\u30a4\u30eb\u30d1\u30b9\u307e\u305f\u306f\u30d5\u30a9\u30eb\u30c0\u30d1\u30b9\u3092\u5165\u529b"))
        self.button_3 = wx.Button(self.record_append_panel, wx.ID_ANY, _(u"\u53c2\u7167"))
        self.button_4 = wx.Button(self.record_append_panel, wx.ID_ANY, _(u"\u8ffd\u52a0"))
        self.sizer_13_staticbox = wx.StaticBox(self.record_append_panel, wx.ID_ANY, _(u"\u30ec\u30b3\u30fc\u30c9\u8ffd\u52a0"))
        self.database_delete_panel = wx.Panel(self, wx.ID_ANY)
        self.record_delete_button = wx.Button(self.database_delete_panel, wx.ID_ANY, _(u"\u5168\u30ec\u30b3\u30fc\u30c9\u524a\u9664"))
        self.table_delete_button = wx.Button(self.database_delete_panel, wx.ID_ANY, _(u"\u5168\u30c6\u30fc\u30d6\u30eb\u524a\u9664"))
        self.sizer_16_staticbox = wx.StaticBox(self.database_delete_panel, wx.ID_ANY, _(u"\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u524a\u9664"))
        self.database_construction_panel = wx.Panel(self, wx.ID_ANY)
        self.checkbox_1 = wx.CheckBox(self.database_construction_panel, wx.ID_ANY, _(u"\u30c7\u30d5\u30a9\u30eb\u30c8\u306eSQL\u30d5\u30a1\u30a4\u30eb\u3092\u5229\u7528\u3059\u308b"))
        self.text_ctrl_5 = wx.TextCtrl(self.database_construction_panel, wx.ID_ANY, _(u"\u5229\u7528\u3059\u308bSQL\u30d5\u30a1\u30a4\u30eb\u306e\u30d5\u30a1\u30a4\u30eb\u30d1\u30b9\u3092\u5165\u529b"))
        self.button_8 = wx.Button(self.database_construction_panel, wx.ID_ANY, _(u"\u53c2\u7167"))
        self.button_7 = wx.Button(self.database_construction_panel, wx.ID_ANY, _(u"\u69cb\u7bc9"))
        self.sizer_23_staticbox = wx.StaticBox(self.database_construction_panel, wx.ID_ANY, _(u"\u30c7\u30fc\u30bf\u30d9\u30fc\u30b9\u69cb\u7bc9"))
        self.result_panel = wx.Panel(self, wx.ID_ANY)
        self.list_ctrl_3 = wx.ListCtrl(self.result_panel, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DataModificationPane.__set_properties
        self.record_append_panel.SetMinSize((456, 90))
        self.database_delete_panel.SetMinSize((456, 60))
        self.database_construction_panel.SetMinSize((456, 110))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DataModificationPane.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_28 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_23_staticbox.Lower()
        sizer_23 = wx.StaticBoxSizer(self.sizer_23_staticbox, wx.HORIZONTAL)
        sizer_24 = wx.BoxSizer(wx.VERTICAL)
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_16_staticbox.Lower()
        sizer_16 = wx.StaticBoxSizer(self.sizer_16_staticbox, wx.HORIZONTAL)
        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_13_staticbox.Lower()
        sizer_13 = wx.StaticBoxSizer(self.sizer_13_staticbox, wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_15.Add(self.text_ctrl_4, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_15.Add(self.button_3, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_14.Add(sizer_15, 1, wx.EXPAND, 0)
        sizer_14.Add(self.button_4, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_13.Add(sizer_14, 1, wx.EXPAND, 0)
        self.record_append_panel.SetSizer(sizer_13)
        sizer_12.Add(self.record_append_panel, 0, wx.TOP | wx.EXPAND, 10)
        sizer_17.Add(self.record_delete_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_17.Add(self.table_delete_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_16.Add(sizer_17, 1, wx.EXPAND, 0)
        self.database_delete_panel.SetSizer(sizer_16)
        sizer_12.Add(self.database_delete_panel, 0, wx.TOP | wx.EXPAND, 10)
        sizer_25.Add(self.checkbox_1, 0, wx.ALL, 5)
        sizer_27.Add(self.text_ctrl_5, 1, 0, 0)
        sizer_27.Add(self.button_8, 0, 0, 0)
        sizer_25.Add(sizer_27, 1, wx.EXPAND, 0)
        sizer_25.Add(self.button_7, 0, wx.ALIGN_RIGHT, 0)
        sizer_24.Add(sizer_25, 1, wx.EXPAND, 0)
        sizer_23.Add(sizer_24, 1, wx.EXPAND, 0)
        self.database_construction_panel.SetSizer(sizer_23)
        sizer_12.Add(self.database_construction_panel, 0, wx.TOP | wx.EXPAND, 10)
        sizer_28.Add(self.list_ctrl_3, 1, wx.EXPAND, 0)
        self.result_panel.SetSizer(sizer_28)
        sizer_12.Add(self.result_panel, 1, wx.TOP | wx.EXPAND, 10)
        self.SetSizer(sizer_12)
        sizer_12.Fit(self)
        # end wxGlade

# end of class DataModificationPane

class SignatureEstimationPane(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SignatureEstimationPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.signature_estimation_object_panel = wx.Panel(self, wx.ID_ANY)
        self.signature_estimation_object_text_ctrl = wx.TextCtrl(self.signature_estimation_object_panel, wx.ID_ANY, _(u"\u30d5\u30a1\u30a4\u30eb\u30d1\u30b9\u307e\u305f\u306f\u30d5\u30a9\u30eb\u30c0\u30d1\u30b9\u3092\u5165\u529b"))
        self.signature_estimation_object_file_reference_button = wx.Button(self.signature_estimation_object_panel, wx.ID_ANY, _(u"\u30d5\u30a1\u30a4\u30eb\u53c2\u7167"))
        self.signature_estimation_object_directory_reference_button = wx.Button(self.signature_estimation_object_panel, wx.ID_ANY, _(u"\u30d5\u30a9\u30eb\u30c0\u53c2\u7167"))
        self.sizer_1_staticbox = wx.StaticBox(self.signature_estimation_object_panel, wx.ID_ANY, _(u"\u63a8\u5b9a\u5bfe\u8c61"))
        self.signature_estimation_execution_panel = wx.Panel(self, wx.ID_ANY)
        self.signature_estimation_execution_button = wx.Button(self.signature_estimation_execution_panel, wx.ID_ANY, _(u"\u63a8\u5b9a"))
        self.signature_estimation_result_panel = wx.Panel(self, wx.ID_ANY)
        self.signature_estimation_result_list_ctrl = wx.ListCtrl(self.signature_estimation_result_panel, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnFileRefButtonClick, self.signature_estimation_object_file_reference_button)
        self.Bind(wx.EVT_BUTTON, self.OnDirRefButtonClick, self.signature_estimation_object_directory_reference_button)
        self.Bind(wx.EVT_BUTTON, self.OnExeButtonClick, self.signature_estimation_execution_button)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SignatureEstimationPane.__set_properties
        self.signature_estimation_object_panel.SetMinSize((456, 80))
        # end wxGlade
        
        init_list_ctrl(self)

    def __do_layout(self):
        # begin wxGlade: SignatureEstimationPane.__do_layout
        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_1_staticbox.Lower()
        sizer_1 = wx.StaticBoxSizer(self.sizer_1_staticbox, wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.signature_estimation_object_text_ctrl, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.signature_estimation_object_file_reference_button, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(self.signature_estimation_object_directory_reference_button, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.signature_estimation_object_panel.SetSizer(sizer_1)
        sizer_18.Add(self.signature_estimation_object_panel, 0, wx.TOP | wx.EXPAND, 10)
        sizer_21.Add(self.signature_estimation_execution_button, 0, wx.BOTTOM | wx.ALIGN_RIGHT, 20)
        self.signature_estimation_execution_panel.SetSizer(sizer_21)
        sizer_18.Add(self.signature_estimation_execution_panel, 0, wx.EXPAND, 0)
        sizer_22.Add(self.signature_estimation_result_list_ctrl, 1, wx.EXPAND, 0)
        self.signature_estimation_result_panel.SetSizer(sizer_22)
        sizer_18.Add(self.signature_estimation_result_panel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_18)
        sizer_18.Fit(self)
        # end wxGlade

    def OnFileRefButtonClick(self, event):  # wxGlade: SignatureEstimationPane.<event_handler>
        on_file_ref_button_click(self)

    def OnDirRefButtonClick(self, event):  # wxGlade: SignatureEstimationPane.<event_handler>
        on_dir_ref_button_click(self)

    def OnExeButtonClick(self, event):  # wxGlade: SignatureEstimationPane.<event_handler>
        on_exe_button_click(self)

# end of class SignatureEstimationPane

class MainWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWindow.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.frame_statusbar = self.CreateStatusBar(1, 0)
        self.main_notebook = wx.Notebook(self, wx.ID_ANY, style=0)
        self.learning_estimation_pane = LearningEstimationPane(self.main_notebook, wx.ID_ANY)
        self.tuning_pane = TuningPane(self.main_notebook, wx.ID_ANY)
        self.data_modification_pane = DataModificationPane(self.main_notebook, wx.ID_ANY)
        self.signature_estimation_pane = SignatureEstimationPane(self.main_notebook, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWindow.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((480, 512))
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = [_("frame_statusbar")]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        self.main_notebook.SetBackgroundColour(wx.Colour(240, 240, 240))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWindow.__do_layout
        root_layout = wx.BoxSizer(wx.VERTICAL)
        self.main_notebook.AddPage(self.learning_estimation_pane, _(u"\u5b66\u7fd2\u30d9\u30fc\u30b9\u63a8\u5b9a"))
        self.main_notebook.AddPage(self.tuning_pane, _(u"\u30c1\u30e5\u30fc\u30cb\u30f3\u30b0"))
        self.main_notebook.AddPage(self.data_modification_pane, _(u"\u5b66\u7fd2\u30c7\u30fc\u30bf\u5909\u66f4"))
        self.main_notebook.AddPage(self.signature_estimation_pane, _(u"\u30b7\u30b0\u30cd\u30c1\u30e3\u30d9\u30fc\u30b9\u63a8\u5b9a"))
        root_layout.Add(self.main_notebook, 1, wx.EXPAND, 0)
        self.SetSizer(root_layout)
        self.Layout()
        # end wxGlade

# end of class MainWindow
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame = MainWindow(None, wx.ID_ANY, "")
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()